// Lazy loader for the distilled research text. Each school × topic note lives in its
// own JSON file (src/content/<topic>/<school>.json, generated by
// scripts/build_site_content.py) and is code-split into its own chunk, so the raw
// research text is only fetched when a parent opens that specific school page.

import { normalizeMetric, orderMetricKeys, type Metric } from './metrics.ts'
import { stampFor } from './localizeData.ts'
import type { ContentSection, SchoolTopicContent } from './types.ts'

const loaders = import.meta.glob<SchoolTopicContent>('../content/*/*.json')

function keyFor(topicSlug: string, schoolSlug: string): string {
  return `../content/${topicSlug}/${schoolSlug}.json`
}

/**
 * Retrieval bookkeeping that belongs to the repo, not to a parent reading a
 * school page: who ran the fetch, on whose behalf, with which Wayback/CDX
 * query. The ingest pipeline lifts these headers verbatim out of the source
 * `.md`, so they arrive as ordinary sections.
 *
 * Dropped at load, not deleted from the JSON — the data-provenance standard
 * requires the repo keep the trail, and source-material/ keeps it too. The
 * substantive sections of the same note (rate tables, snapshot lists, computed
 * year-over-year changes) are unaffected and still render.
 */
const INTERNAL_SUBTOPICS = /^provenance$/i

/**
 * A section whose entire body is the source document's own `# Title` line.
 * Ingest lifts that H1 as a section, so the card renders its own heading twice
 * — once as chrome, once as untranslatable English body text. No content is
 * lost by dropping it: the heading is already the card's title.
 */
function isTitleOnly(text: string): boolean {
  const t = text.trim()
  return t.startsWith('# ') && !t.includes('\n')
}

function isInternal(section: ContentSection): boolean {
  if (INTERNAL_SUBTOPICS.test((section.subtopic ?? '').trim())) return true
  return isTitleOnly(section.text ?? '')
}

export function hasContent(topicSlug: string, schoolSlug: string): boolean {
  return keyFor(topicSlug, schoolSlug) in loaders
}

/* ---------------------------------------------------------- translations -- */

type ContentOverlay = { blocks: Record<string, string> }

const CONTENT_OVERLAYS = new Map<string, Record<string, string> | undefined>()

/*
 * DEFERRED behind a function — `import.meta.glob` cannot be parsed by plain
 * Node, and the build-time checkers import this module directly.
 */
function overlayFiles() {
  return import.meta.glob<ContentOverlay>('../data/overlays/*.content.*.json', {
    import: 'default',
  })
}

/** Warms the content overlay for a topic+locale; resolves once ready. */
export async function loadContentOverlay(topicSlug: string, lang: string): Promise<void> {
  const key = `${topicSlug}:${lang}`
  if (CONTENT_OVERLAYS.has(key)) return
  const load = overlayFiles()?.[`../data/overlays/${topicSlug}.content.${lang}.json`]
  if (!load) {
    CONTENT_OVERLAYS.set(key, undefined)
    return
  }
  try {
    CONTENT_OVERLAYS.set(key, (await load()).blocks)
  } catch {
    // A missing or malformed overlay must not break the page: English stands in.
    CONTENT_OVERLAYS.set(key, undefined)
  }
}

/**
 * Swap each translated block inside a section body.
 *
 * Blocks are keyed by a hash of their English text, so a block the ingest
 * pipeline reordered still resolves, and a block it EDITED simply misses and
 * renders English — the same safe failure the src/data overlays have.
 *
 * Verbatim blocks (rate tables, quoted Wayback snapshots) were never extracted,
 * so they miss by construction and stay English, which is what keeps them
 * checkable against the school's own archived page.
 */
function localizeBody(text: string, blocks: Record<string, string>): string {
  return text
    .split(/(\n\s*\n)/)
    .map((part) => (/^\s*$/.test(part) ? part : (blocks[stampFor(part.replace(/\s+$/, ''))] ?? part)))
    .join('')
}

export type MetricGroup = {
  metric: Metric
  sections: ContentSection[]
}

/**
 * Results already computed this session, keyed by topic×school×lang.
 *
 * This exists for LAYOUT STABILITY, not speed. `loadMetricGroups` is async, so
 * a component must render *something* on its first pass — a "Loading research…"
 * placeholder — and swap in the real cards on a second pass. On a pre-rendered
 * page that is actively harmful: the served HTML already contains the full
 * research, so React tore down ~1700px of real content, showed seven one-line
 * placeholders for ~55ms, then put it back. Measured CLS 0.32, over 3x the
 * 0.1 threshold, and visible as the whole page jumping.
 *
 * With a synchronous cache, a caller can ask whether the answer is already
 * known (`peekMetricGroups`) and render the real thing on the FIRST pass, so
 * there is no swap and no shift. The async path is unchanged for a cold load,
 * where a placeholder is honest — nothing has been fetched yet.
 */
const GROUPS_CACHE = new Map<string, MetricGroup[]>()

function groupsKey(topicSlug: string, schoolSlug: string, lang: string): string {
  return `${topicSlug}:${schoolSlug}:${lang}`
}

/**
 * The cached result for a school×topic, or undefined if it has not been loaded
 * yet. Synchronous by design — this is what lets a component skip the
 * placeholder render entirely when the data is already in hand.
 *
 * Returns undefined (not []) for a note that does not exist, so "not loaded"
 * and "loaded, genuinely empty" stay distinguishable; the empty case is a real
 * result and IS cached.
 */
export function peekMetricGroups(
  topicSlug: string,
  schoolSlug: string,
  lang = 'en',
): MetricGroup[] | undefined {
  return GROUPS_CACHE.get(groupsKey(topicSlug, schoolSlug, lang))
}

/**
 * Load a school×topic note and group its sections under canonical metrics
 * (hidden/internal sections are dropped). Returns [] if the note doesn't exist.
 */
export async function loadMetricGroups(
  topicSlug: string,
  schoolSlug: string,
  lang = 'en',
): Promise<MetricGroup[]> {
  const cached = GROUPS_CACHE.get(groupsKey(topicSlug, schoolSlug, lang))
  if (cached) return cached
  const loader = loaders[keyFor(topicSlug, schoolSlug)]
  if (!loader) {
    GROUPS_CACHE.set(groupsKey(topicSlug, schoolSlug, lang), [])
    return []
  }
  const mod = await loader()
  const data = (mod as { default?: SchoolTopicContent }).default ?? (mod as SchoolTopicContent)

  /* Undefined for English and for any topic with no overlay — `localizeBody`
     is then skipped entirely and sections pass through by reference. */
  const blocks = lang === 'en' ? undefined : CONTENT_OVERLAYS.get(`${topicSlug}:${lang}`)

  const byKey = new Map<string, MetricGroup>()
  const order: string[] = []
  for (const section of data.sections) {
    if (isInternal(section)) continue
    const metric = normalizeMetric(topicSlug, section.subtopic)
    if (!metric) continue
    let group = byKey.get(metric.key)
    if (!group) {
      group = { metric, sections: [] }
      byKey.set(metric.key, group)
      order.push(metric.key)
    }
    group.sections.push(
      blocks
        ? {
            ...section,
            /* The heading renders as its own <h3>, so it is looked up whole
               rather than through localizeBody's block splitter. */
            subtopic: blocks[stampFor(section.subtopic.trim())] ?? section.subtopic,
            text: localizeBody(section.text, blocks),
          }
        : section,
    )
  }
  const result = orderMetricKeys(topicSlug, order).map((k) => byKey.get(k)!)
  /* Cached per LANGUAGE as well as per school×topic: the overlay above rewrites
     the section bodies, so an `es` result must never be served to an `en`
     reader. Keyed by groupsKey(), which includes lang. */
  GROUPS_CACHE.set(groupsKey(topicSlug, schoolSlug, lang), result)
  return result
}
