// Lazy loader for the distilled research text. Each school × topic note lives in its
// own JSON file (src/content/<topic>/<school>.json, generated by
// scripts/build_site_content.py) and is code-split into its own chunk, so the raw
// research text is only fetched when a parent opens that specific school page.

import { normalizeMetric, orderMetricKeys, type Metric } from './metrics.ts'
import type { ContentSection, SchoolTopicContent } from './types.ts'

const loaders = import.meta.glob<SchoolTopicContent>('../content/*/*.json')

function keyFor(topicSlug: string, schoolSlug: string): string {
  return `../content/${topicSlug}/${schoolSlug}.json`
}

/**
 * Retrieval bookkeeping that belongs to the repo, not to a parent reading a
 * school page: who ran the fetch, on whose behalf, with which Wayback/CDX
 * query. The ingest pipeline lifts these headers verbatim out of the source
 * `.md`, so they arrive as ordinary sections.
 *
 * Dropped at load, not deleted from the JSON — the data-provenance standard
 * requires the repo keep the trail, and source-material/ keeps it too. The
 * substantive sections of the same note (rate tables, snapshot lists, computed
 * year-over-year changes) are unaffected and still render.
 */
const INTERNAL_SUBTOPICS = /^provenance$/i

function isInternal(section: ContentSection): boolean {
  return INTERNAL_SUBTOPICS.test((section.subtopic ?? '').trim())
}

export function hasContent(topicSlug: string, schoolSlug: string): boolean {
  return keyFor(topicSlug, schoolSlug) in loaders
}

export type MetricGroup = {
  metric: Metric
  sections: ContentSection[]
}

/**
 * Load a school×topic note and group its sections under canonical metrics
 * (hidden/internal sections are dropped). Returns [] if the note doesn't exist.
 */
export async function loadMetricGroups(
  topicSlug: string,
  schoolSlug: string,
): Promise<MetricGroup[]> {
  const loader = loaders[keyFor(topicSlug, schoolSlug)]
  if (!loader) return []
  const mod = await loader()
  const data = (mod as { default?: SchoolTopicContent }).default ?? (mod as SchoolTopicContent)

  const byKey = new Map<string, MetricGroup>()
  const order: string[] = []
  for (const section of data.sections) {
    if (isInternal(section)) continue
    const metric = normalizeMetric(topicSlug, section.subtopic)
    if (!metric) continue
    let group = byKey.get(metric.key)
    if (!group) {
      group = { metric, sections: [] }
      byKey.set(metric.key, group)
      order.push(metric.key)
    }
    group.sections.push(section)
  }
  return orderMetricKeys(topicSlug, order).map((k) => byKey.get(k)!)
}
