// Triage verdicts for the sibling-detector queue. Keyed by English string;
// `langs` narrows a verdict to specific locales where it differs.
export const TRIAGE = {
// ---------- LEAK: department / subject-category names beside translated siblings ----------
'Health & Fitness':            {v:'LEAK', why:'Department name in a departments list whose 8 siblings (Science, English, Mathematics, Arts…) are all translated.'},
'Health and Wellness':         {v:'LEAK', why:'Course name beside a translated Physical Education in the same course list.'},
'Health Education':            {v:'LEAK', why:'Course name beside translated Science / Social Studies / Physical Education siblings.'},
'Biblical Studies':            {v:'LEAK', why:'Department name; every sibling department is translated.'},
'Library / Information Literacy':{v:'LEAK', why:'Course name beside a translated Physical Education in the same list.'},
'Academic Technology':         {v:'LEAK', why:'Course name; the descriptive course siblings in the department are translated.'},
'World Language Rotation':     {v:'LEAK', why:'Descriptive course name — "rotation" is prose; the sibling description is translated.'},
'Physical Education':          {v:'LEAK', why:'Department/course name translated by 7 locales and in sibling lists in this locale.'},
'Physical Education/Health':   {v:'LEAK', why:'Compound of two translated department words; siblings Required/Elective are translated.'},
'Early Childhood':             {v:'LEAK', why:'Division band label beside translated Middle (5-8) / Upper (9-12) / Lower (K-4).'},
'Early Childhood Program':     {v:'LEAK', why:'Course-list entry beside translated Language Arts / Science / Social Studies / Mathematics.'},
'Junior Kindergarten':         {v:'LEAK', why:'Grade-level name beside translated First Grade / Second Grade / Third Grade / Fourth Grade.'},
'Options Program / Pathways Program':{v:'LEAK', why:'Support-track department beside translated Science/Social Studies/English/Physical Education.'},
'Health Occupations Students of America':{v:'KEEP', why:'Official national organisation name (HOSA); the club catalog keeps org names verbatim.'},
'Structured Literacy':         {v:'LEAK', why:'Pedagogical approach, not a title — descriptive prose in a course slot.'},
'Guided Academic Support':     {v:'LEAK', why:'Descriptive support-service label; the surrounding support prose is translated.'},
'Learning Academy':            {v:'LEAK', why:'Descriptive support-programme label beside translated Intervention / Therapies on site.'},
'Spanish Immersion':           {v:'LEAK', why:'Category filter chip beside translated All / Arts / Athletics / Faith.'},
'STEM & Engineering':          {v:'LEAK', why:'Category filter chip beside translated All / Athletics / Cooking / Faith.'},
'Governance / leadership':     {v:'LEAK', why:'Catalog category beside translated Affinity / Service / Academic.'},
'Leadership / media':          {v:'KEEP', langs:['it'], why:'Both words are Italian loanwords already; the correct rendering is byte-identical (ledger precedent, PR #190).'},
'High School Courses':         {v:'LEAK', why:'Division title beside translated Lower School Courses / Middle School Courses.'},
'Middle School Courses':       {v:'LEAK', why:'Division title beside translated grade-band siblings in the same divisions list.'},
'Upper School Courses':        {v:'LEAK', why:'Division title beside translated grade-band siblings in the same divisions list.'},
'Science: Forces of Change':   {v:'LEAK', why:'"Science:" prefix is translated in every sibling; the title carries prose.'},
'History 7: A More Perfect Union':{v:'KEEP', langs:['bn'], why:'Course title; the sibling History 6 keeps its "History 6:" prefix in Latin too, translating only the descriptive tail — same shape, and bn did translate that tail elsewhere. Catalog-matchable title.'},
'Band / Strings / Choir':      {v:'LEAK', why:'Three common subject words in a course slot; the locale translates each word elsewhere.'},
'Spanish I / French I / Mandarin I':{v:'KEEP', why:'Course codes with roman numerals — a family matches these against the published catalog.'},
'Acts and the Early Church + Case for Christ':{v:'KEEP', why:'Named curriculum units; the sibling prose keeps them verbatim inside a translated sentence ("পড়ানো হয় Acts and the Early Church").'},
'AFAR International Research': {v:'KEEP', why:'Named programme (AFAR); catalog identifier.'},
'Art Studio I–IV':             {v:'KEEP', why:'Course code with roman-numeral range; catalog-matchable.'},
'Dual Enrollment: Public Speaking':{v:'LEAK', why:'The bare "Dual Enrollment" label IS translated in the same list (Matrícula dual); only the two full course lines were skipped.'},
'Dual Enrollment: Introduction to Sociology':{v:'LEAK', why:'Same group as above — "Dual Enrollment" translated beside it.'},
'Dual enrollment':             {v:'LEAK', why:'Lower-case common noun in a depth-category slot beside translated Mathematics / Science.'},
'Introduction to Philosophy: Human Person':{v:'LEAK', langs:['fa'], why:'Course title whose siblings Ethics and Logic ARE translated in this locale, along with both course descriptions.'},
'Intro to Sports Medicine':    {v:'LEAK', why:'Course title; the sibling description "Fundamentals of sports medicine…" is translated.'},
'Introduction to Sports Medicine':{v:'LEAK', why:'Same course under its long name; sibling "An introduction to sports medicine." is translated.'},
'Strength Training':           {v:'LEAK', why:'Course title; the sibling technique description is translated.'},
'Weight Training':             {v:'LEAK', why:'Course title; the sibling description is translated.'},
'Ultimate Frisbee':            {v:'KEEP', why:'Sport name — the roster convention keeps bare sport names as identifiers (ledger precedent: te sport names, PR #190).'},
'P.E. — Dancercise II':        {v:'KEEP', langs:['es'], why:'Course code with a roman numeral and a coined brand word (Dancercise); catalog-matchable.'},
'Language Arts & Life Fitness':{v:'LEAK', langs:['fr'], why:'Two subject-area words in a course slot; fr translates both words elsewhere (Fine Arts electives -> Options Fine Arts shows the pattern).'},
'French, Spanish & Mandarin Exposure':{v:'LEAK', langs:['fr'], why:'"Exposure" is prose; the sibling sentence "Students are exposed to French, Spanish, and…" is translated.'},
'Selected Language of Study':  {v:'LEAK', langs:['fr'], why:'Descriptive phrase, not a course code; the sibling sentence explaining it is translated.'},
'Restoration & Sustainability':{v:'KEEP', why:'Named Covenant Day high-school department with its own director — the sibling prose calls it "a named department".'},
'Advanced Topics':             {v:'KEEP', why:'Named course category (the "AT" in school-designed AT courses); catalog-matchable.'},
// ---------- LEAK: figure / score-table row labels ----------
'SAT Math — 2025':             {v:'LEAK', why:'Score-table row label; "SAT total — 2025" is translated in the same table.'},
'SAT EBRW — 2025':             {v:'LEAK', why:'Same table, same shape as the translated SAT total rows.'},
'Before School Care':          {v:'LEAK', why:'Fact label beside translated Sign-ups / Staggered dismissal in the same facts card.'},
'Before Care 7:30–8:15am':     {v:'LEAK', why:'Add-on label; the sibling "After Care to 4:30pm" IS translated in the same list.'},
'Relax/Choice Time':           {v:'LEAK', why:'Schedule-item prose kept while 11 siblings in the same published-afternoon card are translated.'},
// ---------- KEEP: proper nouns, venues, named awards, orgs ----------
'Hoffman Riley Court':         {v:'KEEP', why:'Named venue.'},
'Latin Arts Association':      {v:'KEEP', why:'Named parent/faculty organisation.'},
'Friends of the Arts':         {v:'KEEP', why:'Named parent volunteer organisation.'},
'Spotlight on the Arts':       {v:'KEEP', why:'Named recurring event.'},
'Arts Jam · Cabaret':          {v:'KEEP', why:'Named season events.'},
'Edinburgh Fringe':            {v:'KEEP', why:'Named festival.'},
'Governor’s School':           {v:'KEEP', why:'Named NC state programme.'},
'Scholastic Art Awards':       {v:'KEEP', why:'Named national award programme.'},
'Christians in Theatre Arts (CITA)':{v:'KEEP', why:'Named organisation with its acronym.'},
'Apple Distinguished School':  {v:'KEEP', why:'Named Apple certification.'},
'Metrolina Athletic Conference':{v:'KEEP', why:'Named athletic conference.'},
'NC Mr. Basketball':           {v:'KEEP', why:'Named state award.'},
'NC Mr. Football + All-Americans':{v:'KEEP', why:'Named state award plus a named national honour.'},
'Gatorade Player of the Year': {v:'KEEP', why:'Named national award.'},
'Gatorade Players of the Year':{v:'KEEP', why:'Named national award, plural.'},
'Strength of America Award':   {v:'KEEP', why:'Named award.'},
'Patriot Athletic Hall of Fame':{v:'KEEP', why:'Named school hall of fame.'},
'USA Lacrosse All-Americans':  {v:'KEEP', why:'Named national honour.'},
"McDonald's All-Americans":    {v:'KEEP', why:'Named national honour.'},
'Wells Fargo Cup':             {v:'KEEP', why:'Named state trophy.'},
'Wells Fargo Cups':            {v:'KEEP', why:'Named state trophy, plural.'},
'Wachovia / Wells Fargo Cups': {v:'KEEP', why:'Named state trophy under both sponsor names.'},
'NASCAR Cup Series':           {v:'KEEP', why:'Named racing series.'},
'Battle of the Books':         {v:'KEEP', why:'Named competition.'},
'Johnson Scholarship, Washington & Lee (2026)':{v:'KEEP', why:'Named scholarship at a named university.'},
'SMU Hunt Leadership Scholars Program':{v:'KEEP', why:'Named scholarship programme.'},
'St. Augustine Scholars Program':{v:'KEEP', why:'Named school programme.'},
'February One Scholarship (NC A&T)':{v:'KEEP', why:'Named scholarship.'},
'QuestBridge Scholar → Stanford':{v:'KEEP', why:'Named programme plus a university name; the arrow is punctuation.'},
'Family Individualized Tuition (FIT)':{v:'KEEP', why:'Named diocesan tuition programme with its acronym.'},
'The Educational Resource Program':{v:'KEEP', why:'Named in-house programme (already a ledger KEEP for fr, PR #190).'},
'Junior Classical League chapter':{v:'KEEP', langs:['te'], why:'Named national organisation; "chapter" alone is not enough to make the string prose.'},
'Students Advocating for Gender Equality':{v:'KEEP', why:'Official club name as printed in the catalog.'},
'Promoting Respect, Inclusion and Safety for Sexual Minorities':{v:'KEEP', why:'Official club name (PRISM) spelled out as printed.'},
"Super Women's Affinity Group":{v:'KEEP', why:'Official affinity-group name as printed.'},
'DECA, Debate, Model UN, Latin Club':{v:'KEEP', why:'Four organisation names in a list.'},
'Science Olympiad, Envirothon, Battle of the Books, Model UN':{v:'KEEP', why:'Four named competitions.'},
'National Honor Society (28 in ’25), Global Studies Diploma, Acclaim Scholars':{v:'KEEP', why:'Three named programmes/awards (already a bn ledger KEEP, PR #190).'},
'Speech and Debate':           {v:'KEEP', langs:['ar'], why:'Club name; ar keeps club identifiers in Latin, translating only the descriptive columns beside them.'},
'Digital Art and Graphic Design':{v:'KEEP', why:'Course-catalog title in a media list.'},
'Digital Art, Graphics, and Anime':{v:'KEEP', why:'Course-catalog title in a media list.'},
'Studio Art · Art History · Music Theory':{v:'KEEP', why:'Three AP course-catalog titles separated by middots.'},
'Studio Art (2-D & 3-D) · Art History':{v:'KEEP', why:'Course-catalog titles with their dimension qualifiers.'},
'hand-building, wheel throwing, glazing, firing':{v:'KEEP', langs:['fa'], why:'Technique list in visual.media[].detail — fa keeps these verbatim by convention (ledger, PR #190).'},
'Improv & Musical Review':     {v:'KEEP', why:'Named enrichment offering (already a fr/it ledger KEEP, PR #190).'},
'Blumey Best Show':            {v:'KEEP', why:'Named award category.'},
'2026 Blumey — Best Actress':  {v:'KEEP', why:'Named award category with its year.'},
'Musical (Blumey)':            {v:'LEAK', langs:['es'], why:'es translates the sibling "One-Acts (NCTC)" to "Piezas breves (NCTC)" — the same shape, common noun plus a parenthesised proper noun.'},
'One-Acts (NCTC)':             {v:'LEAK', langs:['fr'], why:'fr translates the sibling "Musical (Blumey)" to "Comédie musicale (Blumey)" — same shape, so keeping this one is the lone exception.'},
'Musical (Upper School)':      {v:'KEEP', why:'"Musical" is a loanword in these locales (hi ledger precedent, PR #190) and Upper School is a kept identifier.'},
'Upper School Musical':        {v:'KEEP', langs:['hi'], why:'Same as above — hi keeps Musical as a loanword and Upper School as an identifier.'},
'Mock Trial art 2nd NC':       {v:'KEEP', langs:['te'], why:'Named competition plus a rank token; the sibling ranks (Chess 2nd place) that te translated carry a full word it could translate.'},
'Mike Hazel, NSCA CSCS.':      {v:'KEEP', why:'Person name plus certification acronyms.'},
'varsity baseball':            {v:'KEEP', langs:['hi'], why:'hi keeps varsity and baseball as loanwords (ledger, PR #190).'},
'Cross Country / Track':       {v:'KEEP', why:'Bare sport names as roster identifiers (ledger precedent, PR #190).'},
'Girls Basketball':            {v:'KEEP', why:'Bare sport name as a roster identifier.'},
'Softball · MS Girls Basketball':{v:'LEAK', langs:['ar'], why:'ar translates every sibling sport in this same coaching roster (Football, Girls Basketball, Boys Basketball, Boys Soccer) — this row is the lone exception.'},
'Football · Asst. AD Facilities':{v:'LEAK', why:'The role half is prose; the sibling "Football QBs · Game Day Coordinator" is translated in the same roster.'},
'Asst AD · Boys Basketball':   {v:'LEAK', langs:['it'], why:'it translates Athletic Director and Guidance Director in the same roster; the abbreviated form is the lone exception.'},
'Athletic Director':           {v:'KEEP', why:'Standing ledger KEEP (2026-08-19) — the per-locale-consistency override.'},
'Director of Athletics':       {v:'KEEP', why:'Same class as Athletic Director; bn/te keep bare Director titles in Latin (ledger, PR #190).'},
'Assoc. Director':             {v:'KEEP', langs:['te'], why:'Bare Director job title; te keeps the class (ledger, PR #190).'},
'College Counselor':           {v:'KEEP', langs:['te'], why:'Bare job title beside a kept Director; same class.'},
'Volleyball · Guidance Director':{v:'KEEP', langs:['fr'], why:'Sport name plus a bare Director title — both kept classes.'},
'Strength & Conditioning':     {v:'KEEP', why:'Role label already triaged and settled 2026-08-19 (PR #151) — bn/it keep it.'},
// ---------- KEEP: division / grade-band identifiers ----------
'Lower School (TK–5)':         {v:'KEEP', why:'Division identifier with its grade span; kept in Latin by every locale.'},
'Lower School (JK–4)':         {v:'KEEP', why:'Division identifier with its grade span.'},
'Lower School (JrK–4)':        {v:'KEEP', why:'Division identifier with its grade span.'},
'Middle School (5–8)':         {v:'KEEP', why:'Division identifier with its grade span.'},
'Middle School (6–8)':         {v:'KEEP', why:'Division identifier with its grade span.'},
'Lower School · PS–4th':       {v:'KEEP', why:'Division identifier plus a grade token; the translated siblings all carry an extra prose word (weekly enrolment, drop-in).'},
'Middle School · 5th–8th':     {v:'KEEP', why:'Same shape as above.'},
// ---------- KEEP: grade/time and money labels (the standing convention) ----------
'JK–K · Bridge 2:20–3:15':     {v:'KEEP', why:'Grade tokens plus a clock span, and Bridge is a named programme; per the grade/time convention nothing translatable remains.'},
'Gr 1–4 · Bridge 2:40–3:35':   {v:'KEEP', why:'Same shape as above.'},
'After School Program · 3:00–6:00 · $3,784/yr':{v:'KEEP', why:'Programme name, clock span and a figure — the grade/time convention leaves nothing.'},
'AM 8:30-12pm or PM 12:30-3:30pm':{v:'LEAK', why:'"or" is prose and AM/PM are translatable markers in these locales; the sibling tier labels are translated.'},
'Camp Victor · 8:30am - 3:30pm':{v:'KEEP', why:'Named camp plus a clock span.'},
'Charger Chill Day Camp · 8am–5pm':{v:'KEEP', why:'Named camp plus a clock span.'},
'College Essay Bootcamp':      {v:'KEEP', why:'Named camp offering.'},
'**College Application Bootcamp**':{v:'KEEP', why:'Named counselling-timeline milestone.'},
'**College Kick-Off**':        {v:'KEEP', langs:['hi'], why:'Named counselling-timeline milestone, same class as College Application Bootcamp.'},
'A Princess Castle Dollhouse Adventure':{v:'KEEP', why:'Named camp offering as printed in the catalog.'},
'Field Experience, gr. 4–12 · $500–1,000':{v:'LEAK', why:'"Field Experience" is a translatable fee name; the siblings Yearbook / Technology / Textbooks ARE translated in the same components list.'},
'Tuition Protection Program · $250/yr':{v:'KEEP', langs:['it'], why:'Named programme plus a figure; the translated siblings are common-noun fee names (Enrollment fee, New family fee).'},
'~30,000 sq ft, 2022':         {v:'KEEP', why:'Figure plus unit — the open converted-units question, not this pass to settle (ledger, PR #190).'},
'~47,000 sq ft, 2022':         {v:'KEEP', why:'Figure plus unit.'},
'50,000 sq ft, 2001':          {v:'KEEP', why:'Figure plus unit.'},
'53,000 sq ft, 2001':          {v:'KEEP', why:'Figure plus unit.'},
'(SEC · Big Ten · ACC · Big 12)':{v:'KEEP', why:'Four named athletic conferences.'},
'ACC · Big Ten · Big 12 · SEC':{v:'KEEP', why:'Four named athletic conferences.'},
// ---------- KEEP: figure-bearing merit/score strings (the te convention, re-verified) ----------
'**7** Finalists · **16** Commended · 8 College Board Achievement Scholars':{v:'KEEP', langs:['te'], why:'te keeps the award-tier tokens (Finalists/Commended/Scholars) and translates only trailing prose — this row has none.'},
'**9** Semifinalists':         {v:'KEEP', langs:['te'], why:'Bare award tier with no trailing prose; nothing left to translate under the te convention.'},
'**7** Semifinalists · **7** Finalists · **2** Commended · 1 Scholar, 1 College-Sponsored Scholar':{v:'LEAK', why:'fr/fa translate the tier words in sibling rows (demi-finalistes, finalistes) — this row is the lone exception.'},
'96% — 38 AP Scholars with Distinction, 27 with Honor, 33 Scholars':{v:'LEAK', why:'"with Distinction"/"with Honor" is prose; the sibling rows carrying class-year prose ARE translated.'},
'11 National Merit Commended Students (2025)':{v:'KEEP', langs:['te'], why:'Award-tier tokens under the te convention; the translated siblings carry non-award prose.'},
'2 National Merit Finalists (2025)':{v:'KEEP', langs:['te'], why:'Same as above.'},
'— Class of 2022 · TO VERIFY':{v:'KEEP', why:'Editorial provenance marker; the sibling that IS translated is the longer sentence form of it.'},
'"multiple Scholastic Art Award winners"':{v:'KEEP', why:'Verbatim quotation naming an award; quoting convention differs per locale (ledger, PR #190).'},
'"Although service is not a graduation requirement at Cannon, students\' deep sense of commitment and personal responsibility is evidenced by the collective completion of almost 10,000 service hours each year through school-wide projects and individual efforts."':{v:'KEEP', why:'Verbatim quotation from the school profile (ledger class, PR #190).'},
'"Due to the small class size and the college-bound nature of Covenant Day’s population, we believe that class rank is not a strong discriminator… Therefore, we do not rank."':{v:'KEEP', why:'Verbatim quotation (already a bn/te ledger KEEP, PR #190).'},
'Belinda Jackson, Afterschool Director (704-531-4034)':{v:'LEAK', why:'"Afterschool Director" is a compound role phrase, not a bare Director title; the siblings Latest pickup / Closed / Enrollment are translated.'},
}
