#!/usr/bin/env node
/**
 * Generate dist/robots.txt and dist/sitemap.xml from the research manifest.
 *
 * Both were 404 on the live site before this shipped, so crawlers had neither
 * an invitation nor a route list. Generated rather than hand-written into
 * public/ deliberately: they are derived from scripts/seo_routes.mjs, which
 * reads src/data/schools.json, so adding a school updates the sitemap with no
 * one remembering to. A hand-written sitemap goes stale silently — it keeps
 * validating while listing five of six schools.
 *
 * Each URL advertises its ?lang= variants with xhtml:link hreflang alternates.
 * The pre-rendered pages are English-only by decision; the other nine locales
 * render client-side from the same URL plus ?lang=, and this is how a crawler
 * is told they exist. x-default points at the bare (English) URL.
 *
 * Usage: node scripts/gen_seo_files.mjs [--quiet]
 * Exit codes: 0 = written, 2 = script/setup error.
 */
import { writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { ROUTES, LOCALES, SITE_ORIGIN, REPO_ROOT, urlFor } from './seo_routes.mjs'

const QUIET = process.argv.includes('--quiet')
const DIST = resolve(REPO_ROOT, 'dist')

/** XML-escape the five predefined entities. URLs contain '&' once ?lang= lands. */
function xml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function robotsTxt() {
  return [
    '# Charlotte School Insights — https://charlotteschoolinsights.com',
    '# Generated by scripts/gen_seo_files.mjs; do not edit dist/ by hand.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    `Sitemap: ${SITE_ORIGIN}/sitemap.xml`,
    '',
  ].join('\n')
}

function sitemapXml(lastmod) {
  const entries = ROUTES.map((route) => {
    const loc = urlFor(route)
    // Every locale, plus x-default. Google wants each alternate set to be
    // self-referential — the page must list itself among its own alternates —
    // so 'en' is included rather than assumed.
    const alternates = [
      ...LOCALES.map(
        (lang) =>
          `      <xhtml:link rel="alternate" hreflang="${lang}" href="${xml(urlFor(route, lang))}" />`,
      ),
      `      <xhtml:link rel="alternate" hreflang="x-default" href="${xml(loc)}" />`,
    ].join('\n')
    return [
      '   <url>',
      `      <loc>${xml(loc)}</loc>`,
      `      <lastmod>${lastmod}</lastmod>`,
      `      <changefreq>${route.changefreq}</changefreq>`,
      `      <priority>${route.priority}</priority>`,
      alternates,
      '   </url>',
    ].join('\n')
  }).join('\n')

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    entries,
    '</urlset>',
    '',
  ].join('\n')
}

async function main() {
  if (!existsSync(DIST)) {
    console.error('gen_seo_files: dist/ not found — run `vite build` first.')
    process.exit(2)
  }
  // Date only, per the sitemap spec's W3C-datetime allowance. Using the build
  // date rather than a per-page git mtime keeps this honest and cheap: it says
  // "this is when the site was last published", which is true of every page.
  const lastmod = new Date().toISOString().slice(0, 10)

  await writeFile(join(DIST, 'robots.txt'), robotsTxt(), 'utf8')
  await writeFile(join(DIST, 'sitemap.xml'), sitemapXml(lastmod), 'utf8')

  if (!QUIET) {
    console.log(`gen_seo_files: wrote robots.txt and sitemap.xml (${ROUTES.length} URLs)`)
  }
}

main().catch((err) => {
  console.error('gen_seo_files: ' + (err?.stack ?? err))
  process.exit(2)
})
