// Per-school brand theming. Hand-maintained (NOT regenerated by the ingest pipeline).
//
// `color` is used as the school's accent throughout the UI. The values below are
// tasteful *approximations* chosen to keep the six schools visually distinct — adjust
// any of them to a school's official brand color as needed; the UI derives light/dark
// tints automatically, so only this one hex per school needs to change.
//
// `initials` is the badge monogram. New schools that appear in schools.json but are
// missing here fall back to a neutral slate color and auto-generated initials.

export type Brand = {
  color: string
  initials: string
}

export const BRANDS: Record<string, Brand> = {
  cannon: { color: '#6d28d9', initials: 'CA' }, // violet
  'charlotte-christian': { color: '#1d3f8f', initials: 'CC' }, // navy
  'charlotte-country-day': { color: '#0f7b52', initials: 'CD' }, // green
  'charlotte-latin': { color: '#166534', initials: 'CL' }, // hunter green
  'davidson-day': { color: '#1e5fd1', initials: 'DD' }, // patriot blue
  'providence-day': { color: '#be123c', initials: 'PD' }, // crimson
}

const FALLBACK_COLOR = '#5b6472'

export function brandFor(slug: string, name: string): Brand {
  const found = BRANDS[slug]
  if (found) return found
  // Derive initials from the display name (e.g. "Queens Grant" -> "QG").
  const initials =
    name
      .replace(/\bSchool\b/gi, '')
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0]?.toUpperCase() ?? '')
      .join('') || slug.slice(0, 2).toUpperCase()
  return { color: FALLBACK_COLOR, initials }
}
