// Per-school brand theming. Hand-maintained (NOT regenerated by the ingest pipeline).
//
// `color` is each school's accent throughout the UI, keyed to its official athletic
// colors (verified July 2026 against each school's athletics/mascot info). Because
// these six schools share a narrow palette — three lean navy/blue — the blues are
// graded dark→bright so the schools stay visually distinct. The UI derives light/dark
// tints from this one hex automatically, so only the hex needs to change.
//
// `initials` is the badge monogram. New schools that appear in schools.json but are
// missing here fall back to a neutral slate color and auto-generated initials.
//
// `logo` is the school's official athletics mascot mark, shown on the school-page header.
// Files live in `public/logos/<slug>.png` (transparent PNG). Provenance + source URLs
// for each are in `source-material/branding/<slug>/`. These are trademarked marks kept
// for a private research tool; schools without a logo simply show no crest.

// `welcomeVideoUrl` is the school's own introduction video, embedded above the
// research areas on its dossier page. Must be an **embed** URL, not a watch or
// share link — `https://www.youtube.com/embed/<id>` for YouTube, or
// `https://player.vimeo.com/video/<id>` for Vimeo. Optional — schools without
// one hide the Welcome Video section and its two TOC entries.
//
// Both hosts work with no component branching: WelcomeVideo passes this straight
// into <iframe src> and has no provider-specific logic, so the only thing that
// matters is that the URL is embeddable. Trinity Episcopal publishes on Vimeo;
// every other school to date is YouTube.

// `city` is the municipality in the school's own published mailing address, and it
// drives the dossier kicker ("School dossier · Gastonia, NC"). Five of the eleven
// schools are not in Charlotte, so this is REQUIRED rather than optional: a new
// school with no city is a compile error, not a page that silently claims Charlotte.
// Verified 2026-08-23 against each school's own site; addresses and source URLs are
// in `source-material/branding/_shared/`. The state is NOT stored here — every school
// is in NC, and the abbreviation lives in each locale's kicker string as chrome.

// `homepageUrl` is the school's own homepage ROOT — the link behind the school
// name and the mascot crest in the dossier header, opening in a new tab. Root
// only, never a deep link: a parent clicking our `<h1>` should land where the
// school's own front door is, and an admissions or athletics sub-page rots far
// faster than a homepage does. `scripts/check_schoolurls.mjs` enforces that shape
// (https, no path beyond `/`, no query or fragment) plus uniqueness across schools.
//
// OPTIONAL, like `logo` and `welcomeVideoUrl`. A school with no `homepageUrl`
// renders its name as plain text rather than a broken link, the same stance
// HighSchoolPlacement and CollegeSupport already take on an unresolved URL. The
// checker therefore reports coverage as an informational count and does NOT fail
// on a gap — a gate nobody can drive to zero stops being read.
//
// It lives HERE rather than on the `School` record in schools.json for the same
// load-bearing reason as `city` and `hasHighSchool`: the ingest pipeline REBUILDS
// every schools.json school record as bare `{slug, name}` from the source-material
// folder names, so a URL written there is erased by the next ingest run with no
// error and no failing check.
//
// All twelve were re-verified live on 2026-09-17 before being written here;
// statuses, final URLs and two traps (Carmel Christian answers 503 to a bare curl
// while being perfectly up; Charlotte Christian is the lone `.com`) are recorded in
// `source-material/branding/_shared/All Schools - Branding - Campus City and Address.md`.
// The checker deliberately makes no network call — liveness is a dated record there,
// not a build gate that fails on someone else's outage.

// `hasHighSchool` is the PreK-8 flag, and it is FALSE only for a school that
// ends at 8th grade. Absent or true means ordinary K-12 behaviour, so every
// existing school needs no entry — the flag is opt-in to the exception, not a
// field every school must carry.
//
// It lives HERE, in hand-maintained per-school config, rather than on the
// `School` record in schools.json, and that placement is load-bearing: the
// ingest pipeline REBUILDS every schools.json school record as bare
// `{slug, name}` from the source-material folder names
// (.claude/skills/ingest-source-material/build_docs.py:187), so a flag written
// into that file is silently erased by the next ingest run. A PreK-8 school
// would quietly rejoin the Compare page with no error and no failing check.
//
// What it drives: a school with no 9th-12th grade is excluded from the Compare
// page entirely (see `comparableSchools` in lib/manifest.ts) and shows no
// per-topic Compare button on its own dossier. It is NOT what hides College
// Support or shows High School Placement — those follow the standing
// absence-not-emptiness rule and need no flag at all.

export type Brand = {
  color: string
  initials: string
  city: string
  logo?: string
  welcomeVideoUrl?: string
  homepageUrl?: string
  hasHighSchool?: boolean
}

export const BRANDS: Record<string, Brand> = {
  cannon: {
    color: '#8a2433', // Cougars — maroon & gold
    initials: 'CA',
    city: 'Concord',
    homepageUrl: 'https://www.cannonschool.org/',
    logo: '/logos/cannon.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/dI5x4KEkBSY',
  },
  'carmel-christian': {
    // Cougars — navy & red. #13294b is a deep navy distinct from Latin's
    // #12294f and Covenant Day's #002855. (Both 'CC' — Charlotte Christian —
    // and 'CA' — Cannon — are taken, so the badge uses 'CM' for CarMel.)
    color: '#13294b',
    initials: 'CM',
    city: 'Matthews',
    homepageUrl: 'https://www.carmelchristian.org/',
    welcomeVideoUrl: 'https://www.youtube.com/embed/0ILLfsxWGYg', // user-chosen, 2026-08-16
  },
  'charlotte-catholic': {
    // Cougars — LIGHT BLUE, white & red (Wikipedia's infobox; the planning note
    // said "green and gold", which is wrong and would also have collided with
    // Charlotte Country Day's #107a43). The hue is the school's OWN: #75b2dd is
    // the accent in charlottecatholic.org's theme stylesheet (nav hover, callout
    // blocks, mobile sub-nav header). That raw value is only 2.29:1 against
    // white, and .badge fills with --brand behind #fff text while --brand also
    // renders as a text color on light surfaces, so it is deepened along the
    // same hue (204.8°) to #3a759e — 4.98:1 white-on-badge, WCAG AA. It is the
    // only light-to-mid blue in the set: 62 RGB units from its nearest
    // neighbour (Davidson Day's #1e5fd1) and far from every navy.
    // The school's red (#d7102a) is its other brand color but is a near-twin of
    // Providence Day's #be123c, so the blue is the right accent to carry.
    color: '#3a759e',
    // 'CC' (Charlotte Christian), 'CA' (Cannon), 'CM' (Carmel), 'CD' (Country
    // Day), 'CL' (Latin) and 'CV' (Covenant Day) are all taken — 7 of 11 badges
    // start with C. 'CK' for Charlotte CatholiK is wrong; this uses the school's
    // own common abbreviation CCHS reduced to its distinctive pair.
    initials: 'CH',
    city: 'Charlotte',
    homepageUrl: 'https://www.charlottecatholic.org/',
    welcomeVideoUrl: 'https://www.youtube.com/embed/mk06OtSv9ps', // user-chosen, 2026-08-18
  },
  'charlotte-christian': {
    color: '#1e40af', // Knights — royal blue & white
    initials: 'CC',
    city: 'Charlotte',
    homepageUrl: 'https://www.charlottechristian.com/',
    logo: '/logos/charlotte-christian.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/Be0ULPLDrMM',
  },
  'charlotte-country-day': {
    color: '#107a43', // Buccaneers — green & gold
    initials: 'CD',
    city: 'Charlotte',
    homepageUrl: 'https://www.charlottecountryday.org/',
    logo: '/logos/charlotte-country-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/voNR9UF346g',
  },
  'charlotte-latin': {
    color: '#12294f', // Hawks — navy & white
    initials: 'CL',
    city: 'Charlotte',
    homepageUrl: 'https://www.charlottelatin.org/',
    logo: '/logos/charlotte-latin.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/QvM-MuKndus',
  },
  'covenant-day': {
    // Lions — blue & gold (MaxPreps). #002855 is the site's own CSS
    // `primary-color` custom property (covenantday.org, checked 2026-08-15) —
    // the darkest navy in the set, distinct from Latin's #12294f.
    color: '#002855',
    initials: 'CV', // 'CD' is taken by Charlotte Country Day's badge
    city: 'Matthews',
    homepageUrl: 'https://www.covenantday.org/',
    welcomeVideoUrl: 'https://www.youtube.com/embed/sqXDmXq2zXY', // user-chosen, 2026-08-16
  },
  'davidson-day': {
    color: '#1e5fd1', // Patriots — red, white & navy
    initials: 'DD',
    city: 'Davidson',
    homepageUrl: 'https://www.davidsonday.org/',
    logo: '/logos/davidson-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/wTYvCc7FXCs',
  },
  'gaston-day': {
    // Spartans — navy & gold. #00263f is SAMPLED from the school's own wordmark
    // (gaston-day-logo-blue-gold-01.png on gastonday.org), not eyeballed from a
    // screenshot: the logo's dominant non-white pixel bucket quantizes to
    // #002840, and the crest carries a lighter #183060. The planning note
    // expected a near-collision needing a nudge — it turned out not to. At
    // #00263f this is the DARKEST and most cyan-leaning navy in the set, clearly
    // separable from Hickory Grove's #14396e and Charlotte Latin's #12294f
    // (both lighter and more violet) and from Covenant Day's #002855 (more
    // blue, less green). No adjustment was needed, so the badge is the school's
    // real color rather than a distinguishable approximation of it.
    // The brand also carries a real gold (#c8a058, ~10.9k pixels of the
    // wordmark) — the planning note's "navy + white, no secondary accent" was
    // wrong. Brand has no secondary-color field, so the gold is recorded here
    // rather than dropped.
    color: '#00263f',
    initials: 'GD', // confirmed by the GD monogram on the school's crest
    city: 'Gastonia',
    homepageUrl: 'https://www.gastonday.org/',
    welcomeVideoUrl: 'https://www.youtube.com/embed/f1ohuLbiKJI', // user-chosen, 2026-08-18
  },
  'hickory-grove-christian': {
    // Lions — navy & gold. #14396e is a mid-navy chosen to stay distinct from the
    // other blues: Covenant Day's #002855 (also "Lions — blue & gold") and
    // Charlotte Latin's #12294f are darker, Charlotte Christian's #1e40af is
    // brighter. Initials 'HG' — HG/HGC not otherwise taken.
    color: '#14396e',
    initials: 'HG',
    city: 'Charlotte',
    homepageUrl: 'https://www.hgchristian.org/',
    welcomeVideoUrl: 'https://www.youtube.com/embed/hhtjvy5tCVE', // user-chosen, 2026-08-17
  },
  'providence-day': {
    color: '#be123c', // Chargers — red, white & navy
    initials: 'PD',
    city: 'Charlotte',
    homepageUrl: 'https://www.providenceday.org/',
    logo: '/logos/providence-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/EfrQPAWsqv8',
  },
  'trinity-episcopal': {
    // Wildcats. The school's own stylesheet declares one primary, #002d56, and
    // the logo corroborates it exactly (465,595 px of it, two orders of
    // magnitude ahead of any other color). That raw value sits 5.1 RGB units
    // from Covenant Day's #002855 — visually the same navy, in the most crowded
    // part of this palette (Covenant Day, Gaston Day #00263f, Carmel #13294b,
    // Latin #12294f and Hickory Grove #14396e are all in it). So it is graded
    // along the school's OWN hue (208.6°, full saturation) until it clears every
    // neighbour: 41.4 units from Hickory Grove, 43.4 from Charlotte Christian,
    // 60.6 from Covenant Day. 8.86:1 white-on-badge, WCAG AAA. Same treatment
    // already applied to Charlotte Catholic. The school's secondary #006f51 is a
    // button green that appears nowhere in the mark, so it is not the accent.
    color: '#004a8e',
    // No other badge starts with T; TES is the school's own abbreviation and its
    // crest monogram, reduced to its distinctive pair.
    initials: 'TE',
    city: 'Charlotte',
    homepageUrl: 'https://www.tescharlotte.org/',
    logo: '/logos/trinity-episcopal.png',
    // K-8: no grades 9-12. Drives Compare exclusion — see the note above.
    hasHighSchool: false,
    // Trinity publishes on Vimeo, not YouTube. "Say Yes to TES" (1:25, Apr 2026),
    // embed_privacy: anywhere. Note player.vimeo.com returns 401 to a header-less
    // curl regardless of Referer — that is Vimeo bot-blocking, not an embed
    // restriction, and it renders fine in the app.
    welcomeVideoUrl: 'https://player.vimeo.com/video/1179403154',
  },
}

const FALLBACK_COLOR = '#5b6472'

export function brandFor(slug: string, name: string): Brand {
  const found = BRANDS[slug]
  if (found) return found
  // Derive initials from the display name (e.g. "Queens Grant" -> "QG").
  const initials =
    name
      .replace(/\bSchool\b/gi, '')
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0]?.toUpperCase() ?? '')
      .join('') || slug.slice(0, 2).toUpperCase()
  // Unknown-slug path only — every school in BRANDS carries its own verified city.
  return { color: FALLBACK_COLOR, initials, city: 'Charlotte' }
}
