// Per-school brand theming. Hand-maintained (NOT regenerated by the ingest pipeline).
//
// `color` is each school's accent throughout the UI, keyed to its official athletic
// colors (verified July 2026 against each school's athletics/mascot info). Because
// these six schools share a narrow palette — three lean navy/blue — the blues are
// graded dark→bright so the schools stay visually distinct. The UI derives light/dark
// tints from this one hex automatically, so only the hex needs to change.
//
// `initials` is the badge monogram. New schools that appear in schools.json but are
// missing here fall back to a neutral slate color and auto-generated initials.
//
// `logo` is the school's official athletics mascot mark, shown on the school-page header.
// Files live in `public/logos/<slug>.png` (transparent PNG). Provenance + source URLs
// for each are in `source-material/branding/<slug>/`. These are trademarked marks kept
// for a private research tool; schools without a logo simply show no crest.

// `welcomeVideoUrl` is the school's own introduction video, embedded above the
// research areas on its dossier page. Must be a YouTube **embed** URL
// (`https://www.youtube.com/embed/<id>`), not a watch/share link. Optional —
// schools without one hide the Welcome Video section and its two TOC entries.

export type Brand = {
  color: string
  initials: string
  logo?: string
  welcomeVideoUrl?: string
}

export const BRANDS: Record<string, Brand> = {
  cannon: {
    color: '#8a2433', // Cougars — maroon & gold
    initials: 'CA',
    logo: '/logos/cannon.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/dI5x4KEkBSY',
  },
  'carmel-christian': {
    // Cougars — navy & red. #13294b is a deep navy distinct from Latin's
    // #12294f and Covenant Day's #002855. (Both 'CC' — Charlotte Christian —
    // and 'CA' — Cannon — are taken, so the badge uses 'CM' for CarMel.)
    color: '#13294b',
    initials: 'CM',
    welcomeVideoUrl: 'https://www.youtube.com/embed/0ILLfsxWGYg', // user-chosen, 2026-08-16
  },
  'charlotte-catholic': {
    // Cougars — LIGHT BLUE, white & red (Wikipedia's infobox; the planning note
    // said "green and gold", which is wrong and would also have collided with
    // Charlotte Country Day's #107a43). The hue is the school's OWN: #75b2dd is
    // the accent in charlottecatholic.org's theme stylesheet (nav hover, callout
    // blocks, mobile sub-nav header). That raw value is only 2.29:1 against
    // white, and .badge fills with --brand behind #fff text while --brand also
    // renders as a text color on light surfaces, so it is deepened along the
    // same hue (204.8°) to #3a759e — 4.98:1 white-on-badge, WCAG AA. It is the
    // only light-to-mid blue in the set: 62 RGB units from its nearest
    // neighbour (Davidson Day's #1e5fd1) and far from every navy.
    // The school's red (#d7102a) is its other brand color but is a near-twin of
    // Providence Day's #be123c, so the blue is the right accent to carry.
    color: '#3a759e',
    // 'CC' (Charlotte Christian), 'CA' (Cannon), 'CM' (Carmel), 'CD' (Country
    // Day), 'CL' (Latin) and 'CV' (Covenant Day) are all taken — 7 of 11 badges
    // start with C. 'CK' for Charlotte CatholiK is wrong; this uses the school's
    // own common abbreviation CCHS reduced to its distinctive pair.
    initials: 'CH',
    welcomeVideoUrl: 'https://www.youtube.com/embed/mk06OtSv9ps', // user-chosen, 2026-08-18
  },
  'charlotte-christian': {
    color: '#1e40af', // Knights — royal blue & white
    initials: 'CC',
    logo: '/logos/charlotte-christian.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/Be0ULPLDrMM',
  },
  'charlotte-country-day': {
    color: '#107a43', // Buccaneers — green & gold
    initials: 'CD',
    logo: '/logos/charlotte-country-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/voNR9UF346g',
  },
  'charlotte-latin': {
    color: '#12294f', // Hawks — navy & white
    initials: 'CL',
    logo: '/logos/charlotte-latin.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/QvM-MuKndus',
  },
  'covenant-day': {
    // Lions — blue & gold (MaxPreps). #002855 is the site's own CSS
    // `primary-color` custom property (covenantday.org, checked 2026-08-15) —
    // the darkest navy in the set, distinct from Latin's #12294f.
    color: '#002855',
    initials: 'CV', // 'CD' is taken by Charlotte Country Day's badge
    welcomeVideoUrl: 'https://www.youtube.com/embed/sqXDmXq2zXY', // user-chosen, 2026-08-16
  },
  'davidson-day': {
    color: '#1e5fd1', // Patriots — red, white & navy
    initials: 'DD',
    logo: '/logos/davidson-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/wTYvCc7FXCs',
  },
  'gaston-day': {
    // Spartans — navy & gold. #00263f is SAMPLED from the school's own wordmark
    // (gaston-day-logo-blue-gold-01.png on gastonday.org), not eyeballed from a
    // screenshot: the logo's dominant non-white pixel bucket quantizes to
    // #002840, and the crest carries a lighter #183060. The planning note
    // expected a near-collision needing a nudge — it turned out not to. At
    // #00263f this is the DARKEST and most cyan-leaning navy in the set, clearly
    // separable from Hickory Grove's #14396e and Charlotte Latin's #12294f
    // (both lighter and more violet) and from Covenant Day's #002855 (more
    // blue, less green). No adjustment was needed, so the badge is the school's
    // real color rather than a distinguishable approximation of it.
    // The brand also carries a real gold (#c8a058, ~10.9k pixels of the
    // wordmark) — the planning note's "navy + white, no secondary accent" was
    // wrong. Brand has no secondary-color field, so the gold is recorded here
    // rather than dropped.
    color: '#00263f',
    initials: 'GD', // confirmed by the GD monogram on the school's crest
    welcomeVideoUrl: 'https://www.youtube.com/embed/f1ohuLbiKJI', // user-chosen, 2026-08-18
  },
  'hickory-grove-christian': {
    // Lions — navy & gold. #14396e is a mid-navy chosen to stay distinct from the
    // other blues: Covenant Day's #002855 (also "Lions — blue & gold") and
    // Charlotte Latin's #12294f are darker, Charlotte Christian's #1e40af is
    // brighter. Initials 'HG' — HG/HGC not otherwise taken.
    color: '#14396e',
    initials: 'HG',
    welcomeVideoUrl: 'https://www.youtube.com/embed/hhtjvy5tCVE', // user-chosen, 2026-08-17
  },
  'providence-day': {
    color: '#be123c', // Chargers — red, white & navy
    initials: 'PD',
    logo: '/logos/providence-day.png',
    welcomeVideoUrl: 'https://www.youtube.com/embed/EfrQPAWsqv8',
  },
}

const FALLBACK_COLOR = '#5b6472'

export function brandFor(slug: string, name: string): Brand {
  const found = BRANDS[slug]
  if (found) return found
  // Derive initials from the display name (e.g. "Queens Grant" -> "QG").
  const initials =
    name
      .replace(/\bSchool\b/gi, '')
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0]?.toUpperCase() ?? '')
      .join('') || slug.slice(0, 2).toUpperCase()
  return { color: FALLBACK_COLOR, initials }
}
